### ISSUE TITLE
Broken links to objects records point to "add?[...]"

### ISSUE THREAD

**Issue by gioele** [cceh/atom#5]
The links in the _Popular this week_ widget have the correct title but they all point to `/a/index.php/mea/add?0%5BdisableNestedSetUpdating%5D=0`.

Something similar happens for all the links to other records in archival descriptions. For example, in `index.php/mea-lw-v-sp-bw-1957-09-27` the links to `Koch, Josef`, `Koch, J.` in "Context area" and in "Access points" all link to `add?`.

**Comment by gioele** [comment]
After a series of tests I have found out that this bug is not present in the upstream Atom code. We introduced this bug in the code dump of 2014-09-05 (31e9418c74142980a5742d094d5cb5448bd16de8) or in one of the preceding commits.

**Comment by gioele** [comment]
The bisection has pointed out commit 279f8e0459fd4a7a42d37659136591a8a3fcd034 (the first code dump from Bernhard) as source of this error.

**Comment by strec** [comment]
The "most popular" template is situated in `atom/apps/qubit/modules/default/templates/_popular.php`.

The php-line of interest is:

```
 <a href="<?php echo url_for(array($object)) ?>">
```

When changing it to

```
 <a href="<?php echo url_for(array($object, 'module' => 'informationobject')) ?>">
```

the problem can be circumvented.

It is unclear, what is causing the problem exactly. The `$object` given to the`url_for` function is no different from the working official atom version. Probably somewhere deep down, when a String is expected, there is an Object instead.

The function `url_for()` belongs to `atom/vendor/symfony/lib/helper/UrlHelper.php`. It calls `url_for1`. This one calls `symfony/lib/controller/sfWebController.class.php`'s function `genUrl`.
In there, ultimately the function `symfony/lib/routing/sfRoute.class.php/generate(...)` is called.
